apiVersion: v1
kind: Service
metadata:
  name: eugene-service-auth
  namespace: eugene
spec:
  selector:
    app: eugene-auth
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001 
  type: ClusterIP 
