apiVersion: apps/v1
kind: Deployment
metadata: 
  name: eugene-deployment-client
  namespace: eugene
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: eugene-client
  template:
    metadata:
      labels:
        app: eugene-client
    spec:
      containers:
        - name: client  
          image: ugindev/client:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_SERVER_URL
              value: "http://acb1d8c05429a4b45815dcf82b7f8012-42938708.us-east-2.elb.amazonaws.com"  
