apiVersion: apps/v1
kind: Deployment
metadata: 
  name: eugene-deployment-discounts
  namespace: eugene
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: eugene-discounts
  template:
    metadata:
      labels:
        app: eugene-discounts
    spec:
      containers:
        - name: discounts
          image: ugindev/discounts:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"

            - name: MONGODB_URI
              value: "mongodb://eugene-service-mongo:27017/resturanty"
            
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: eugene-secrets
                  key: CLOUD_NAME

            - name: CLOUD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: eugene-secrets
                  key: CLOUD_API_KEY

            - name: CLOUD_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: eugene-secrets
                  key: CLOUD_API_SECRET
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: eugene-secrets
                  key: SECRET

          readinessProbe:
            httpGet:
              path: /api/discounts/health
              port: 3002
            initialDelaySeconds: 6
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/discounts/health
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 20
            
