apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: restaurant-ingress
  namespace: eugene
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: restaurant.eugene.local
      http:
        paths:

          # ---------- FRONTEND ----------
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eugene-service-client
                port:
                  number: 3000

          # ---------- AUTH SERVICE ----------
          - path: /api/auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: eugene-service-auth
                port:
                  number: 3001

          # ---------- ITEMS SERVICE ----------
          - path: /api/items(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: eugene-service-items
                port:
                  number: 3003

          # ---------- DISCOUNTS SERVICE ----------
          - path: /api/discounts(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: eugene-service-discounts
                port:
                  number: 3002