apiVersion: v1
kind: Secret
metadata:
  name: eugene-secrets
  namespace: eugene
type: Opaque
stringData:
  CLOUD_NAME: "ddkyayygh"
  CLOUD_API_KEY: "213645815487398"
  CLOUD_API_SECRET: "YLvU7lTHAaVKHY00H-a9Xk304ew"
  SECRET: "MySecret1!"  